apiVersion: v1
kind: ConfigMap
metadata:
  name: country-info-service-config
  namespace: country-integration
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  DB_URL: "jdbc:mysql://mysql:3306/countrydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  DB_POOL_SIZE: "10"
  SOAP_URL: "http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso"
  SOAP_CONNECT_TIMEOUT: "2s"
  SOAP_READ_TIMEOUT: "5s"
  JAVA_OPTS: "-XX:MaxRAMPercentage=75 -XX:+ExitOnOutOfMemoryError"
