apiVersion: v1
kind: Secret
metadata:
  name: country-info-secret
  namespace: country-integration
type: Opaque
stringData:
  DB_USERNAME: countryapp
  DB_PASSWORD: countrypass
  MYSQL_ROOT_PASSWORD: root
